---
name: Build Java PR

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@391291faed854696b72011112b756a115d97a41e
    secrets: inherit
