---
name: Build Java PR

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@3df422f56e7a061ed1be92f567f330a88a624af1
    secrets: inherit
