---
name: Build Java PR

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_java_callable.yml@5b12738d33ba4668b9f764508600c8658e284253
    secrets: inherit
