---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@bfb4a34c93da6ccd4029a021679832bc6135a0a1
    secrets: inherit
