---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@9b7e242b9e7c24c35e3af54447a0d7b09f42e9ae
    secrets: inherit
