---
name: Lint files

# yamllint disable-line rule:truthy
on: pull_request

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@23fe0e49858d501e89bc26f0408c2b6b3b408d55 # 1.21.2
    secrets: inherit
