---
name: Lint files

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_linter_callable.yml@dfb5c13b409b5fc495c96d2a93a60081a3d376d8
    secrets: inherit
