---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_pull_request_callable.yml@3dd8ba8fe474ae0a00297b415969bfd08c0dc3ec
    secrets: inherit
