---
name: "Pull Request"

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches-ignore:
      - "release-please--branches--*"

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_pull_request_callable.yml@709a28f7e7fdba9a6248c0003285b52786b2042e
    secrets: inherit
