---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # using a GitHub only release here. Use .github/update_workflows.sh to switch to a Maven release
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@3df422f56e7a061ed1be92f567f330a88a624af1
    secrets: inherit
