---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # using a GitHub only release here. Use .github/update_workflows.sh to switch to a Maven release
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@5072ece8181c2b6a092db68f37b22108ea2e679e
    secrets: inherit
