---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  default:
    # using a GitHub only release here. Use .github/update_workflows.sh to switch to a Maven release
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_release_callable.yml@2e7d46e578da52791b96594c25f7b49723db5f1d
    secrets: inherit
