---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_dry_run_callable.yml@709a28f7e7fdba9a6248c0003285b52786b2042e
    secrets: inherit
