---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_dry_run_callable.yml@bfb4a34c93da6ccd4029a021679832bc6135a0a1
    secrets: inherit
