---
name: Release Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release-dry-run

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/maven_release_dry_run_callable.yml@dee768d29359adc09deb0f097531ae21d47cc3a3
    secrets: inherit
