---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@9b7e242b9e7c24c35e3af54447a0d7b09f42e9ae
    secrets: inherit
