---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@dee768d29359adc09deb0f097531ae21d47cc3a3
    secrets: inherit
