---
name: Approve all Renovate PRs automatically

# yamllint disable-line rule:truthy
on:
  pull_request_target

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_renovate_auto_approve_callable.yml@dfb5c13b409b5fc495c96d2a93a60081a3d376d8
    secrets: inherit
