---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@9b7e242b9e7c24c35e3af54447a0d7b09f42e9ae
    secrets: inherit
