---
name: PR commented

# yamllint disable-line rule:truthy
on:
  issue_comment:
    types:
      - created

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_comment_dispatch_callable.yml@bfb4a34c93da6ccd4029a021679832bc6135a0a1
    secrets: inherit
