---
name: Execute ChatOps command

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types:
      - help-command

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_slash_ops_command_help_callable.yml@219feb99199c88a43ec416656a13aed54b82e7c5
    secrets: inherit
