---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@219feb99199c88a43ec416656a13aed54b82e7c5
    secrets: inherit
