---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_spelling_callable.yml@3dd8ba8fe474ae0a00297b415969bfd08c0dc3ec
    secrets: inherit
