---
name: "Close stale issues and PRs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "25 2 * * *"

jobs:
  default:
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_stale_callable.yml@4d076ad765d2a81430c72e8d96d94c95afc94746
    secrets: inherit
