---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_welcome_message_callable.yml@c73d75a62f409dbb32d739efda04cf5aed255b8f
    secrets: inherit
