---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_welcome_message_callable.yml@bfb4a34c93da6ccd4029a021679832bc6135a0a1
    secrets: inherit
