---
name: PR opened

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened

jobs:
  default:
    # yamllint disable-line rule:line-length
    uses: Hapag-Lloyd/Workflow-Templates/.github/workflows/default_welcome_message_callable.yml@dee768d29359adc09deb0f097531ae21d47cc3a3
    secrets: inherit
